### ISSUE TITLE
Amethyst orbs placing weirdly

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#101]
![image](https://user-images.githubusercontent.com/65736624/124394914-ca14d200-dd01-11eb-9d59-cb9f9ecad169.png)

**Comment by CocoTheOwner** [comment]
![image](https://user-images.githubusercontent.com/65736624/124394939-df89fc00-dd01-11eb-891a-039f38a19c10.png)

**Comment by NextdoorPsycho** [comment]
the watterlogging issue will be fixed soon"tm"
but the fact that an amethyst can generate floating in the middle of a cave, theres notghing i can do about that but lower rate, and lower height so its always in a floor

**Comment by NextdoorPsycho** [comment]
Fixed on branch, Will merge
