### ISSUE TITLE
Animals spawning inside of solid blocks

### ISSUE THREAD

**Issue by Kurenox** [IrisDimensions/overworld#102]
1.4.7
![2021-07-04_11 05 24](https://user-images.githubusercontent.com/86927490/124395259-ec81fd80-dcb7-11eb-97e0-6f006258680a.png)

**Comment by NextdoorPsycho** [comment]
me to polar bear, me too...
This is an issue with the jar, and is already an issue, not much we can do about it yet unfortunately
