### ISSUE TITLE
Leaves/Webs/Bushes/Ice spawning in/under lava

### ISSUE THREAD

**Issue by Kurenox** [IrisDimensions/overworld#103]
1.4.7
![2021-07-04_11 07 39](https://user-images.githubusercontent.com/86927490/124395320-513d5800-dcb8-11eb-8010-03ff61785679.png)

**Comment by NextdoorPsycho** [comment]
this is funny, but  with how the jar is written  its either this, or no decorations in caves, this always has a chance to happen
i could clamp... will test and see
