### ISSUE TITLE
Underwater structures not properly waterlogged

### ISSUE THREAD

**Issue by Kurenox** [IrisDimensions/overworld#104]
1.4.7
![2021-07-04_11 13 23](https://user-images.githubusercontent.com/86927490/124395411-e2acca00-dcb8-11eb-8467-b9c156f24678.png)
Also the stairs are not properly oriented
![2021-07-04_11 15 00](https://user-images.githubusercontent.com/86927490/124395466-20a9ee00-dcb9-11eb-8d0d-05fe1a6b8aba.png)

**Comment by NextdoorPsycho** [comment]
mmmmmmm i see
the rotation on the stairs is because we are rotating less than 90degres and its bugging out, thats an easy fix, but the waterlogging ill look into
tyty

**Comment by NextdoorPsycho** [comment]
Fixed on latest **dab**
