### ISSUE TITLE
Tree growing directly into cliff

### ISSUE THREAD

**Issue by Kurenox** [IrisDimensions/overworld#105]
1.4.7
![2021-07-04_11 17 18](https://user-images.githubusercontent.com/86927490/124395513-71214b80-dcb9-11eb-84de-c4423d2c14f9.png)

**Comment by NextdoorPsycho** [comment]
Thats normal / intended. 
you cant actually tell ingame, just spectator
this is how we better increase volume of trees and not kill performance
