### ISSUE TITLE
Floating blocks and weird meshing where caves meet

### ISSUE THREAD

**Issue by Kurenox** [IrisDimensions/overworld#106]
1.4.7
![2021-07-04_11 20 38](https://user-images.githubusercontent.com/86927490/124395617-ee4cc080-dcb9-11eb-950e-ea2e33c0efc0.png)

**Comment by NextdoorPsycho** [comment]
Intended, this is 2 cave typed colliding, you can change this by removing the style changes, and this is just for better caves imo, go to the desert and see it better there
