### ISSUE TITLE
Large air pocket in ocean

### ISSUE THREAD

**Issue by Kurenox** [IrisDimensions/overworld#109]
![2021-07-04_11 47 53](https://user-images.githubusercontent.com/86927490/124396321-b0ea3200-dcbd-11eb-83aa-84e6c1a56f26.png)
1.4.7
![2021-07-04_11 46 16](https://user-images.githubusercontent.com/86927490/124396309-9617bd80-dcbd-11eb-893b-6183687c7d26.png)

**Comment by NextdoorPsycho** [comment]
cave in an ocean biome, i can drop caves perhaps... will test

**Comment by NextdoorPsycho** [comment]
Dropped bubble rate, try now on latest plz
