### ISSUE TITLE
Tall Sea Grass sticking out past the surface

### ISSUE THREAD

**Issue by Kurenox** [IrisDimensions/overworld#116]
### What happened?

![2021-07-05_11 37 20](https://user-images.githubusercontent.com/86927490/124509123-39340a00-dd86-11eb-990d-eb80222936ff.png)

### What should happen?

It should not.

### Minecraft Version

1.17

### Iris Version

1.4.4

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
dont know what biome this is
