### ISSUE TITLE
Iris versions not appearing in list

### ISSUE THREAD

**Issue by Kurenox** [IrisDimensions/overworld#117]
### What happened?

Versions 1.4.5, 1.4.6, and 1.4.7 do not appear in the Iris versions dropdown list. Also, this new form sucks.

### What should happen?

I don't want to fill like I'm filing my taxes every time I want to report a bug

### Minecraft Version

1.17

### Iris Version

1.4.4

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
The reason for it is that i have people using iris 1.4.4 reporting bugs on 1.16 overworld. this just adds that extra step to ensure i can actually help and its not people being dummies
