### ISSUE TITLE
An outpost without an outpost spawned in the ocean

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#118]
### What happened?

Outpost spawned in the ocean without outpost xD
![image](https://user-images.githubusercontent.com/68811273/124513276-1c79ef80-dde3-11eb-8e17-68e9d842b1f5.png)

### What should happen?

Remove outpost spawn from ocean biome

### Biome

deep_ocean

### Minecraft Version

1.17

### Iris Version

1.4.4

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Patched
