### ISSUE TITLE
Portal rooms spawned ~30 blocks from the stronghold itself and spawned not in the ground, but on the surface

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#122]
### Describe the problem

See title
![image](https://user-images.githubusercontent.com/68811273/124632008-9a460580-de8c-11eb-874e-9304f42f8a72.png)
![image](https://user-images.githubusercontent.com/68811273/124632749-4a1b7300-de8d-11eb-8cde-39ce5504b2f3.png)

### What Should Happen

I really don't know what to write here, well, I'll write an elementary solution here. Just make a check so that the stronghold room spawns not far from each room, or just so that there is a junction of the entrances

### What Biome

tundra/taiga

### Minecraft Version

1.17+

### Iris Version

1.4.9

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
😓

**Comment by NextdoorPsycho** [comment]
Should be working on latest? Reopen if not
