### ISSUE TITLE
A strange mix of stronghold rooms

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#123]
### Describe the problem

See title
![image](https://user-images.githubusercontent.com/68811273/124634101-a03ce600-de8e-11eb-9c36-7e7492e8734f.png)
![image](https://user-images.githubusercontent.com/68811273/124634138-aa5ee480-de8e-11eb-9581-58aef64e0c36.png)
![image](https://user-images.githubusercontent.com/68811273/124635776-7e446300-de90-11eb-87f4-b20970370ed2.png)

### What Should Happen

Raise the room a few blocks higher when spawning
I can't give the name of the room, the `/ir o d `command does not work for me

### Minecraft Version

1.17+

### Iris Version

1.4.9

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
that dust is what its supposed to be lol. (/ir o d)
https://i.imgur.com/bmX8j6x.png
But this can happen with segmentation faults, ill look into the objects myself, can you give me a seed?

**Comment by EneRGO22** [comment]
> that dust is what its supposed to be lol. (/ir o d)
> https://i.imgur.com/bmX8j6x.png
> But this can happen with segmentation faults, ill look into the objects myself, can you give me a seed?

It gave me dust, but when I clicked on an object, a sound sounded and nothing was written to the chat and the object did not glow.
I unfortunately deleted this world already

**Comment by StrangeOne101** [comment]
Confirmed bug, likely to be https://github.com/VolmitSoftware/Iris/issues/367 and https://github.com/VolmitSoftware/Iris/issues/405. But it's almost 100% an issue with Iris itself rather than the overworld pack, so I will close this for now. Thanks for providing extra info about the bug though :)
