### ISSUE TITLE
No loot in chests & barrels

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#135]
### Describe the problem

There's no loot spawning, anywhere.

### What Should Happen

Loot should spawn, instead of not .

### What Biome

Any

### Minecraft Version

1,17

### Iris Version

"LATEST" (1.5.2 from source)

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by StrangeOne101** [comment]
This issue is weird. It happens randomly but then is fine. I wonder if it also relates to mobs not spawning some of the time. It's like any post-generation things the generator has to do just aren't being done sometimes

**Comment by CocoTheOwner** [comment]
Plugin issue. [#462](https://github.com/VolmitSoftware/Iris/issues/462)
