### ISSUE TITLE
Unable to create studio world with 1.5.1 using /ir s create <name>

### ISSUE THREAD

**Issue by DanyGreaver** [IrisDimensions/overworld#136]
### Describe the problem

Unable to create studio world with 1.5.1 using /ir s create <name>
Happens on a server, not localhost 
Using Multiverse, latest stable build
Server jar:  Purpur latest 

### What Should Happen

world should create the default std pack

### Minecraft Version

1.17

### Iris Version

1.5.1

### Relevant log output. (IF APPLICABLE)

https://mclo.gs/H2ufJxj

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Not a full log, no idea what problem you are actually having.
Send try: /iris studio open overworld
and try sending a whole log
