### ISSUE TITLE
Iris 1.5.1 Pregen stuck at 0%

### ISSUE THREAD

**Issue by NipNacks** [IrisDimensions/overworld#137]
### Describe the problem

Iris pregen Chunks/s is constantly stuck at 0% when pregenerating a world

*Issue reupload as the last one was not in the correct format for some reason*

### What Should Happen

Iris pregen Chunks/s shouldn't be at 0 and should pregenerate the world

### Minecraft Version

1.17

### Iris Version

1.5.1

### Relevant log output. (IF APPLICABLE)

https://pastebin.com/KvNzLQWY

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Leave this issue here at, this is not an overworld problem:
https://github.com/VolmitSoftware/Iris/issues
