### ISSUE TITLE
Create new branch for Survival servers

### ISSUE THREAD

**Issue by Inxity** [IrisDimensions/overworld#139]
### Adding, Removing, or Changing

Adding

### Type of Modification

Biome / Region

### What are you trying to modify

I think current overworld is not compatible with Survival servers. Like 
![image](https://user-images.githubusercontent.com/61350916/126083595-004fae4c-0860-4595-a509-aac448931aa6.png)
this picture, you guys could remove these high-profit things in new branch.
Also there are too many grasses on ground, it really affects on players FPS.

### Minecraft Version

1.17.1

### Iris Version

1.5.3

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by Inxity** [comment]
I will review more the current overworld and give you a list of changeable things if you guys are ok with this

**Comment by StrangeOne101** [comment]
I think the estranged plains are fine in survival. They aren't gamebreaking

I also don't know what you mean by "too much grass". Plains biomes have the same amount of grass as in vanilla. If it's taxing on FPS, that's on Mojang, not us. 

You're still free to edit the overworld however you please though. If you don't think it fits your server, no worries! Just make modifications to it

**Comment by CocoTheOwner** [comment]
If you have a list of game-breaking things please do send it 
We aim for a balanced survival experience with an emphasis on exploration, as survival should be.
Wheat isn't high profit though.
If you find anything else, please attach it here.

**Comment by Inxity** [comment]
Wheat is profitable for servers which have market in it, if players obtain that much wheat they can break the economy easily.
I will try sending the list of changeable things.

**Comment by cyberpwnn** [comment]
We have plans for "dimension mods" which allow you to use the same pack, but it adds modifications to the pack itself such as changing terrain heights, removing decorators, replacing blocks, and more.

**Comment by CocoTheOwner** [comment]
If you still want to add a list of to-do's feel free to make a new overworld feature request.
