### ISSUE TITLE
Ruined portals spawn in trees

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#14]
[Found such an unusual bug that the portal spawns in trees](https://prntscr.com/127vpd2)
Biome: temperate-plains and temperate-plains-hills
Overworld versions: v2

**Server and Plugin Informations**
 - Installed plugins: Iris
 - Last build github
 - PaperSpigot 1.16.5 #613]:
 - Operating System (if applicable): 7 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
![2021-04-28_00 14 18](https://user-images.githubusercontent.com/68811273/116475870-161b4480-a883-11eb-80d5-73431fe17b67.png)

**Comment by ArMiN231** [comment]
@RaydenKonig this can be closed due being a problem in the plugin and not a misconfigured pack.

**Comment by CocoTheOwner** [comment]
Would also be fixed with the object priority system

**Comment by RaydenKonig** [comment]
this problem depends on the plugin and not on the package, we will have to wait for an object priority system to be implemented
