### ISSUE TITLE
Outpost meets vaccum

### ISSUE THREAD

**Issue by ArMiN231** [IrisDimensions/overworld#146]
### Describe the problem

![outpost](https://user-images.githubusercontent.com/5337873/126307334-ef06b345-7cba-41b5-af28-0198bed30a0e.png)

### What Should Happen

Not this

### Minecraft Version

1.17.1

### Iris Version

1.5.4

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
what biome is that

**Comment by CocoTheOwner** [comment]
screenshot dum dum

**Comment by NextdoorPsycho** [comment]
this is a problem with vacuum reduced the height of plateau to compensate
