### ISSUE TITLE
Tundra lake is no lake

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#147]
### Describe the problem

![image](https://user-images.githubusercontent.com/65736624/126389422-2ba2d8a8-70a8-4b81-a322-71b5041b4ee3.png)

Tundra lake not creating lakes

### What Should Happen

Either rename tundra lake to not have lake, or add lakes to tundra lake

### What Biome

tundra/tun-lake

### Minecraft Version

1.17

### Iris Version

Built from master https://github.com/VolmitSoftware/Iris/pull/443

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
lol?

**Comment by CocoTheOwner** [comment]
O K

**Comment by NextdoorPsycho** [comment]
its right below you in the picture, the lakes can be rivers, just bad noise gen ig. cant fix this

**Comment by CocoTheOwner** [comment]
Different biome tho, that's not the lake biome. The lake biome is the forest, the beach biome comes next and then there is another.
Teleport to any one of these biome and see what I mean
