### ISSUE TITLE
The ravine when spawning makes the lava behave out of physics

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#15]
I propose to make a smoother entrance of the cave into the ravines

**Server and Plugin Informations**
 - Installed plugins: Iris
 - Last build github
 - PaperSpigot 1.16.5 #613]:
 - Operating System (if applicable): 7 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
 
 - Biome: caves
-  Overworld versions: v2
 
![2021-04-27_22 32 32](https://user-images.githubusercontent.com/68811273/116476793-69da5d80-a884-11eb-82ec-0060914c6f06.png)
![2021-04-27_23 00 22](https://user-images.githubusercontent.com/68811273/116476835-78287980-a884-11eb-806f-064f0ca1df38.png)
![2021-04-29_00 49 02](https://user-images.githubusercontent.com/68811273/116477843-d570fa80-a885-11eb-8379-fb5dfa468ad5.png)

**Comment by CocoTheOwner** [comment]
#16 Turn off vanilla ravines, they're bad and break a lot of things.
I explicitly turned them off for that reason.

**Comment by CocoTheOwner** [comment]
Ravines bad.
