### ISSUE TITLE
Ocean Issue again -  tropcical/tro-rainforest-island

### ISSUE THREAD

**Issue by BenjaminHoegh** [IrisDimensions/overworld#152]
### Describe the problem

![image](https://user-images.githubusercontent.com/22152591/126502436-f15605a9-1351-4d72-be6d-978998565ddd.png)

**IBiome**: ocean/oce-ocean (OCEAN)
**IBIome**: tropcical/tro-rainforest-island (JUNGLE)
**Overworld version**:  3.134

### What Should Happen

Normal oacen?

### What Biome

tropical/tro-rainforest-island

### Minecraft Version

1.17.1

### Iris Version

1.5.6

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Oh I forgot that the new branch of master is stable kek I'll merge it here soon

**Comment by BenjaminHoegh** [comment]
haha okay <3

**Comment by NextdoorPsycho** [comment]
fixed

**Comment by BenjaminHoegh** [comment]
> fixed

Has the fix been published?

**Comment by CocoTheOwner** [comment]
Crossing t's and dotting i's now, should be there today
