### ISSUE TITLE
Broken objects in hot/sav-acacia-denmyre (DESERT)

### ISSUE THREAD

**Issue by BenjaminHoegh** [IrisDimensions/overworld#153]
### Describe the problem

![2021-07-21_21 31 32](https://user-images.githubusercontent.com/22152591/126549164-351e9642-fba2-4393-bb36-9f0769c88d7a.png)

### What Should Happen

I guess there should have been some trees

### What Biome

hot/sav-acacia-denmyre

### Object Id

trees/acacia/denmyre3@131398087, trees/acacia/denmyre4@1811430193, trees/acacia/denmyre6@608287537, trees/acacia/denmyre1@909571517, trees/acacia/denmyre1@882435827

### Minecraft Version

1.17.1

### Iris Version

1.5.6

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [x] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by CocoTheOwner** [comment]
These are the objects Iris was complaining about not being able to find earlier as well. I think it was [this Iris issue](https://github.com/VolmitSoftware/Iris/issues/447)

**Comment by NextdoorPsycho** [comment]
Is this still happening on the latest @BenjaminHoegh ?

**Comment by CocoTheOwner** [comment]
It does. The food I tried isn't working afaik

**Comment by cyberpwnn** [comment]
Could this be a replacer thing? Is that biome using edit tags?

**Comment by CocoTheOwner** [comment]
yes:
```
{
            "chance": 0.3,
            "edit": [
                {
                    "find": [{"block": "spruce_leaves"}],
                    "replace": {"palette": [{
                        "block": "dark_oak_leaves",
                        "data": {"persistent": true}
                    }]}
                },
                {
                    "find": [{"block": "birch_leaves"}],
                    "replace": {"palette": [{
                        "block": "dark_oak_leaves",
                        "data": {"persistent": true}
                    }]}
                },
                {
                    "find": [{"block": "dark_oak_fence"}],
                    "replace": {"palette": [{
                        "block": "dark_oak_leaves",
                        "data": {"persistent": true}
                    }]}
                }
            ],
            "density": 2,
            "rotation": {
                "yAxis": {
                    "min": 0,
                    "max": 0,
                    "interval": 90,
                    "enabled": true
                },
                "enabled": true
            },
            "place": [
                "clutter/oakdenclutt1",
                "clutter/oakdenclutt2",
                "clutter/oakdenclutt3",
                "clutter/oakdenclutt4",
                "clutter/oakdenclutt5",
                "clutter/oakdenclutt6",
                "clutter/oakdenclutt7",
                "clutter/oakdenclutt8",
                "clutter/oakdenclutt9",
                "clutter/oakdenclutt10"
            ],
            "translate": {
                "x": 0,
                "y": -1,
                "z": 0
            }
        }
```

**Comment by CocoTheOwner** [comment]
Maybe it's due to the recent change with the way we handle leaf persistency?

**Comment by BenjaminHoegh** [comment]
Looks like `hot/sav-forest` has the same issue or something familiar

![2021-07-22_21 13 16](https://user-images.githubusercontent.com/22152591/126696428-cb0d328d-83a4-4071-a9ad-95459518145e.png)

**Comment by CocoTheOwner** [comment]
This is an intended object. It's a dead tree.
Try clicking it with `/ir o d` and doing `/ir o p <whatever you got back>`

**Comment by cyberpwnn** [comment]
Im removing all ` "data": {"persistent": true}` tags because iris does this auto now.

**Comment by cyberpwnn** [comment]
Figured it out... ill make a fix for these artifacts later.
