### ISSUE TITLE
Smoother entrance of caves into ravines

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#16]
I propose to make a smoother entrance of the cave into the ravines
Before:
![2021-04-29_00 52 41](https://user-images.githubusercontent.com/68811273/116477563-77dcae00-a885-11eb-826d-a66963aa082c.png)
After: 
![2021-04-29_00 53 35](https://user-images.githubusercontent.com/68811273/116477589-8034e900-a885-11eb-854a-b6899807cee9.png)

**Server and Plugin Informations**
 - Installed plugins: Iris
 - Last build github
 - PaperSpigot 1.16.5 #613]:
 - Operating System (if applicable): 7 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
 
 - Biome: caves
-  Overworld versions: v2

**Comment by CocoTheOwner** [comment]
Ravines are vanilla crap and should be replaced with Iris ravines. That would also make this better, supposedly.

**Comment by CocoTheOwner** [comment]
@EneRGO22 Are you happy with the caves right now? If not, report again in a new issue report, please. Feel free to mention this one.
