### ISSUE TITLE
Hot beach has wrong biome

### ISSUE THREAD

**Issue by BenjaminHoegh** [IrisDimensions/overworld#161]
### Describe the problem

The `hot-beach` has for some unknown reason a cave biome

![2021-07-24_11 26 46](https://user-images.githubusercontent.com/22152591/126864248-0e79ffdc-8157-4930-9fb0-d2c1aa57b19a.png)

### What Should Happen

Should have been a normal `hot-beach` biome

### What Biome

cave/sandy-red-cave

### Minecraft Version

1.17.1

### Iris Version

1.5.9

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Safe to ignore, thats just iris debugging the heightmap, if you are at all below the surface you are in cave domains and that just happens to be where regions poked through! that is safe to ignore, and should not impede gameplay
