### ISSUE TITLE
Straight lines

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#169]
### Describe the problem

Straight lines in biome/region placements:
![image](https://user-images.githubusercontent.com/65736624/126909449-6be63289-441c-495e-a29a-37052153318c.png)
![image](https://user-images.githubusercontent.com/65736624/126909454-5c90bc57-23b8-4105-9e7f-2396fefb9ec1.png)
![image](https://user-images.githubusercontent.com/65736624/126909449-6be63289-441c-495e-a29a-37052153318c.png)

### What Should Happen

Straight lines should not appear, and "proper" interpolation should happen

We can use the latest update with new noise styles & fracturing improvements to make this a reality.

### What Biome

All regions have a chance to

### Minecraft Version

1.17

### Iris Version

1.5.10

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
The latest jar does not fix this?
he just added clover, Clover still runs into this issue. like until that artifact can be resolved there's no real point in trying for a workaround

**Comment by StrangeOne101** [comment]
It seems the lines are back in plains too

![](https://i.imgur.com/NY4D12q.png)

**Comment by NextdoorPsycho** [comment]
Fixed on latest **dab**
