### ISSUE TITLE
Adding familiar cave biomes: Lush caves and Dripstone caves

### ISSUE THREAD

**Issue by DanyGreaver** [IrisDimensions/overworld#172]
### Adding, Removing, or Changing

Adding

### Type of Modification

Biome / Region

### What are you trying to modify

had to put something here but the title says it 

### Minecraft Version

1.17.1

### Iris Version

1.15.13

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
LMAO Telling me to add something is different then an Additive Request, but they have already been planned, and will probably be implemented when the Next update comes out

**Comment by cyberpwnn** [comment]
> LMAO Telling me to add something is different then an Additive Request, but they have already been planned, and will probably be implemented when the Next update comes out

He didn't write the issue template...

**Comment by ArMiN231** [comment]
@NextdoorPsycho done?
