### ISSUE TITLE
Villager dont spawn in village

### ISSUE THREAD

**Issue by XuTianMingX** [IrisDimensions/overworld#178]
### Describe the problem

like title. Villager dont spawn in village. village spawn nothing.

### What Should Happen

Villagers successfully spawn

### What Biome

any

### Minecraft Version

Purpur 1.17.1

### Iris Version

1.6.2

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
yes they do, just tried, 
try /killall all
and wait for a while in a village assuming you are actually seeing animals spawn in general villagers, and pillagers will spawn

**Comment by NextdoorPsycho** [comment]
reopen this if you tried that. otherwise its something on your end
