### ISSUE TITLE
Biomes borders are too smooth #501

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#180]
HySand commented 10 hours ago
Adding, Removing, or Changing

Changing
Type of Modification

Make biomes borders greater
What are you trying to modify

For Biome Blend settings in Video Settings only affect grass block,some biomes' borders which are not consist grass blocks are unsatisfactory .
Border in vanilla world:
https://imgur.com/wNQ5SEZ
Border in Iris world:
https://imgur.com/Sru5DY3
Alternatives

Add extra noise to border?

**Comment by NextdoorPsycho** [comment]
well, we arent vanilla lol
how we do noise will always result in artifacts unless you want static everywhere

**Comment by CocoTheOwner** [comment]
yes plz static thonks

**Comment by NextdoorPsycho** [comment]
really?
I'm not a fan of static but ill do it

**Comment by ArMiN231** [comment]
Can’t satisfy them all

**Comment by NextdoorPsycho** [comment]
see latest
