### ISSUE TITLE
Wood or Log

### ISSUE THREAD

**Issue by HySand** [IrisDimensions/overworld#184]
### Adding, Removing, or Changing

Changing

### Type of Modification

Other

### What are you trying to modify

Woods in loots should be logs i think.

### Minecraft Version

Minecraft 1.17

### Iris Version

1.5.11

### Checklist

- [x] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
Woods in loots should be logs i think.
???
what do you mean

**Comment by StrangeOne101** [comment]
Since 1.13, "Wood" is the term for a 6 sided log. "Planks" is now the official term for crafted wood (no longer just what people call it) and "Log" is just a normal log. 

Iris spawns "wood" in loot chests rather than logs. I agree that it should also be changed to logs

**Comment by NextdoorPsycho** [comment]
Neither of these will be done, we will either have a micro plugin to convert wood to logs and vice versa

**Comment by StrangeOne101** [comment]
?????

The loot table just has to be changed. That's it
