### ISSUE TITLE
Biome suggestion: Amethyst Rainforrest

### ISSUE THREAD

**Issue by adelando** [IrisDimensions/overworld#187]
### Adding, Removing, or Changing

Adding

### Type of Modification

Biome / Region

### What are you trying to modify

These consist of changing leaves to a light magenta colour for leaves and vines, and a light green/bluey tint for the grass

foliage consists of flowering azalea leaf, acacia wood and Allium plus scattered amethyst buds

![2021-08-09_18 46 26](https://user-images.githubusercontent.com/11265974/128703888-72c0ba34-e4b7-4c73-9621-313798b53eee.png)
![2021-08-09_20 07 37](https://user-images.githubusercontent.com/11265974/128703900-a0bbe968-80f4-4452-ae2e-e375f43413ec.png)
![2021-08-09_20 05 26](https://user-images.githubusercontent.com/11265974/128703912-04078fab-e809-4d46-a784-2185e0a7022d.png)
![2021-08-09_18 33 56](https://user-images.githubusercontent.com/11265974/128704281-53faa7db-5fd7-46ed-b629-46c0c0ff4f1f.png)

### Minecraft Version

1.17.1

### Iris Version

na

### Checklist

- [x] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
Can you send me a Schematic of this biome please? like with worldedit make a schematic so i can see the stuff better

**Comment by adelando** [comment]
No worries I’ll load up worldedit when I get a chance and I’ll also attach the biome colours used for leaves and such too

**Comment by adelando** [comment]
Alright, as i cant upload .schems here i uploaded to Google Drive
https://drive.google.com/file/d/1gTWKG2Hmz-vaPegjoL-iqcs00dSg8jCN/view?usp=sharing

Also here is the .json file for the biome in the data pack
https://mcpaste.io/80cd3e5dc87360a4
