### ISSUE TITLE
Smooth and easy cave entrance

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#19]
The entrance to the caves is very bad and it is almost impossible to find it even if the function `"canBreakSurface": true` is enabled, so I propose to make the entrance to the caves smoother and more noticeable so that players can notice this entrance and go into the caves and get resources for themselves

**Comment by CocoTheOwner** [comment]
Caves are placed after terrain generation, not before. This is not achievable without making caves very large.
