### ISSUE TITLE
Bees aren’t spawning

### ISSUE THREAD

**Issue by MrNolex** [IrisDimensions/overworld#198]
### Describe the problem

Beehives without bees… :(
In 1-2 biomes I barely found 1 bee

### What Should Happen

Bees should be spawning

### What Biome

All biome

### Object Id

*

### Minecraft Version

1.17.1

### Iris Version

1.6.6

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by CocoTheOwner** [comment]
What
I just made a PR for this, showed you how to download and use the PR, but you still opened this?
*confusion*
#197

**Comment by MrNolex** [comment]
> What
> I just made a PR for this, showed you how to download and use the PR, but you still opened this?
> _confusion_
> #197

You fixed for 1 biome, right?
But as I saw the other biomes had this issue too. I talked with Nextdoor who said open an issue. 

Sorry if I misunderstood something.

**Comment by CocoTheOwner** [comment]
I think I got all the birch trees with beehives, which other biomes/objects did you also see without bees?

**Comment by MrNolex** [comment]
> I think I got all the birch trees with beehives, which other biomes/objects did you also see without bees?

I add it tomorrow! 🙂

**Comment by MrNolex** [comment]
I coudn't find beehies at oak forest but I found some in this biome: https://imgur.com/a/H5fCU5A
I found a lot of beehives but barely I found only 1 bee

**Comment by NextdoorPsycho** [comment]
latest!
