### ISSUE TITLE
Comfortable and flat bottom in caves

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#20]
Wide caves have too small a bottom for walking and exploring caves
Before and after
![2021-04-29_01 08 30](https://user-images.githubusercontent.com/68811273/116479028-b07d8700-a887-11eb-8f81-a00a5535c8a4.png)
![2021-04-29_01 10 05](https://user-images.githubusercontent.com/68811273/116479055-bb381c00-a887-11eb-9b85-12b52e468027.png)

**Comment by CocoTheOwner** [comment]
the way caves are placed makes this very hard to implement without making caves look very stupid and repetitive.
You can attempt tweaking the cave generation algorithms, perhaps?

**Comment by NextdoorPsycho** [comment]
we'd need to change the jar to be able to add floors to caves, so as of now, im closing this
