### ISSUE TITLE
Add Rayden's old ruins structures (called ruins2 up to & incl. -4)

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#202]
### Adding, Removing, or Changing

Adding

### Type of Modification

Object

### What are you trying to modify

Ruins can be spawning in plains (temperate) and other relatively flat biomes.
Alternatively they can be on top of mountains

### Minecraft Version

1.17.x

### Iris Version

Built from master (has no relation)

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
Not here anymore :(((
