### ISSUE TITLE
Village elements spawn in blocks

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#21]
Village elements can spawn in mountain blocks or other blocks
![2021-04-28_00 13 44](https://user-images.githubusercontent.com/68811273/116479263-00f4e480-a888-11eb-96f2-d4c2753b12d8.png)

**Comment by CocoTheOwner** [comment]
Kinda funny ngl. Not game breaking but worth checking out later on in development

**Comment by NextdoorPsycho** [comment]
This is a Jigsaw problem, and a vacuum problem. The jar will need to be fixed for this to go away
