### ISSUE TITLE
Rare chance of a nether portal at the end of a cave

### ISSUE THREAD

**Issue by ghost** [IrisDimensions/overworld#211]
### Adding, Removing, or Changing

Adding

### Type of Modification

Other

### What are you trying to modify

Add a nether portal at the end of some caves

### Minecraft Version

1.17

### Iris Version

1.8.2

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
need to implement the "cap" system in the the jar
