### ISSUE TITLE
Villages don't spawn villagers

### ISSUE THREAD

**Issue by StrangeOne101** [IrisDimensions/overworld#212]
### Describe the problem

Villages spawn no villagers at all. These need to be initial spawns, and none are spawned.

Tested in temperate biomes

### What Should Happen

They should spawn

### Minecraft Version

1.17

### Iris Version

1.8.3

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
i disagree
![image](https://user-images.githubusercontent.com/29320316/132422534-e735a6f7-3099-4001-a4d2-7752c8a050f9.png)
Fresh install

**Comment by NextdoorPsycho** [comment]
itll be better when the matter system is in full swing
