### ISSUE TITLE
Iron golems on ice

### ISSUE THREAD

**Issue by StrangeOne101** [IrisDimensions/overworld#213]
### Describe the problem

These golems spawn in the middle of nowhere on ice

![2021-09-04_22 19 18](https://user-images.githubusercontent.com/2769013/132091217-07c852dc-7a72-4742-807c-f4e4ac03311b.png)

### What Should Happen

They shouldn't spawn here

### What Biome

Frozen Ocean

### Minecraft Version

1.17

### Iris Version

1.8.3

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
vanilla thing, for some reason they spawn there because the ice represents an igloo lmao, look ta the spawners, there's 0 iron spawners in those places
