### ISSUE TITLE
Remove cactus from the caves

### ISSUE THREAD

**Issue by ArMiN231** [IrisDimensions/overworld#217]
### Adding, Removing, or Changing

Removing

### Type of Modification

Biome / Region

### What are you trying to modify

Remove the cactus from the caves cause it doesnt look natural plus it also breaks a lot

### Minecraft Version

1.17.1

### Iris Version

1.8.6

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by CocoTheOwner** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/132525323-6d3f5b82-694a-4eba-95b9-5ea96fe6ed1f.png)
agreed

**Comment by NextdoorPsycho** [comment]
oop, ok. I never thought of that. removed

**Comment by NextdoorPsycho** [comment]
fixed
