### ISSUE TITLE
Missing Markers for every jigsaw object

### ISSUE THREAD

**Issue by ArMiN231** [IrisDimensions/overworld#221]
### Describe the problem

Missing Markers for every jigsaw object

### What Should Happen

Add those markers

### What Biome

Every biome they appear

### Minecraft Version

1.17

### Iris Version

1.8.10

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Working on 1.9
