### ISSUE TITLE
Village buildings offset too much downwards

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#223]
### Describe the problem

Some village buildings are placed into the ground too much
![image](https://user-images.githubusercontent.com/65736624/133886563-19c7817e-0690-46e5-93c8-7e8b8544c6c0.png)
Sorry for them not being in text, copied them from a stream in Discord

### What Should Happen

These buildings are being placed 1 or 2 blocks too deep into the ground

### What Biome

Any that has a village

### Object Id

See screenshots, sorry :(

### Minecraft Version

1.17.1

### Iris Version

1.8.11

### Relevant log output. (IF APPLICABLE)

-

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by Archy-X** [comment]
Able to reproduce on seed 1384223037562629024 at around 184 81 -273 on Iris 1.9 
![2021-10-13_19 54 27](https://user-images.githubusercontent.com/63976867/137242895-94e0d9fa-9254-4307-8c9d-33cf4d422caf.png)
