### ISSUE TITLE
Lava Caves

### ISSUE THREAD

**Issue by ArMiN231** [IrisDimensions/overworld#225]
### Adding, Removing, or Changing

Adding

### Type of Modification

Biome / Region

### What are you trying to modify

Add lava caves

### Minecraft Version

1.17

### Iris Version

1.8.13

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
They should exist, but the jar is not making them?
