### ISSUE TITLE
Dust of Revealing not working

### ISSUE THREAD

**Issue by GHsorryiwon12345** [IrisDimensions/overworld#226]
### Describe the problem

Dust of Revealing not working

### What Should Happen

Dust of Revealing not working should work

also:

"Cold Penises"

SEED: 2077681968061781640
BIOME: SNOWY TAIGA
COORDS: 137 / 82  / 1638
(around this area)

### What Biome

SNOWY_TAIGA

### Object Id

Can't use

### Minecraft Version

1.17.1

### Iris Version

1.8.13

### Relevant log output. (IF APPLICABLE)

none

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by GHsorryiwon12345** [comment]
Sorry for reporting Dust bug here

**Comment by NextdoorPsycho** [comment]
Not an overworld problem, its placing on a decorator, ill mention it
