### ISSUE TITLE
Floating trees in swamp biome

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#227]
### Describe the problem

![Uploading afbeelding.png…]()

### What Should Happen

No floating trees plz

### What Biome

swamp/sea/ocean-tree (SWAMP)

### Object Id

/ir o d doesn't work, sowwy

### Minecraft Version

1.17.1

### Iris Version

Built from github, but doesn't affect this compared to 1.8.13

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ArMiN231** [comment]
According to @NextdoorPsycho everything is working as intended
