### ISSUE TITLE
Blocks spawn in the ship without water

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#23]
In the ship, the fence, half-blocks and steps spawn without water and it doesn't look very good
![2021-05-15_11 42 43](https://user-images.githubusercontent.com/68811273/118354703-16029080-b575-11eb-93d6-e2c6a65c3dbc.png)
![2021-05-15_11 42 49](https://user-images.githubusercontent.com/68811273/118354711-20248f00-b575-11eb-91f4-b1471e3b6a62.png)

 - Objects: Ships
-  Overworld versions: v2.2

**Comment by CocoTheOwner** [comment]
Unsure why this isn't automatically fixed by Iris. As far as I know Iris automatically waterlogs anything under water level, but that does not seem to be the case here...
This should be easily fixable though with a config setting.

**Comment by CocoTheOwner** [comment]
Also please specify the name of the biome next time; it makes it far easier for us to find the object.

**Comment by NextdoorPsycho** [comment]
This should be auto, ill look into it
