### ISSUE TITLE
Add little more river and lake and some sugar cane

### ISSUE THREAD

**Issue by IPECTER** [IrisDimensions/overworld#231]
### Adding, Removing, or Changing

Adding

### Type of Modification

Biome / Region

### What are you trying to modify

add little more river
add lake (size small and large)
add some sugar cane around water

### Minecraft Version

1.17.1

### Iris Version

1.9

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
There should already be sugarcane by waterbeds, and if not ill look into reimplementing them / upping the rarity
