### ISSUE TITLE
Plain biomes improvement | Leaves

### ISSUE THREAD

**Issue by Mohamad82Bz** [IrisDimensions/overworld#233]
### Adding, Removing, or Changing

Changing

### Type of Modification

Biome / Region

### What are you trying to modify

I feel the leaves generated in plain biome is a bit un-natural or overkill, there are lots of random leaves in the biome that isn't placed nicely, Isn't it better to decrease or use a better noise to generate?

You'll understand what I mean by seeing this picture: 
![image](https://user-images.githubusercontent.com/65306187/135340243-3bbe3ed8-1202-4755-a682-bd6fb33532d5.png)

It feels weird when walking in the biome as a player
Just a small opinion, Coco asked me to post it here.

### Minecraft Version

1.17.1

### Iris Version

1.9

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by Sh3ngsi** [comment]
> 
> 
> What biome is that? Because that looks like LushPlains, but that should be a child. If you can tell me the biome ill fix it

Didn't post this, but figured I would look since there was no response. After searching for a few hours.

![Screenshot_179](https://user-images.githubusercontent.com/90300204/139840273-178ce24d-7957-4972-8b70-ca6c73ea27c5.png)
