### ISSUE TITLE
Dont change ice to water in FROZEN biome

### ISSUE THREAD

**Issue by IPECTER** [IrisDimensions/overworld#235]
### Adding, Removing, or Changing

Adding

### Type of Modification

Object

### What are you trying to modify

Dont change ice to water in FROZEN biome
NEVER CHANGE
plz....
![2021-10-03_12 42 34](https://user-images.githubusercontent.com/80433772/135738812-7fd70e29-99c4-41b1-9f59-ad3bfc16b311.png)

### Minecraft Version

1.17.1

### Iris Version

1.9

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
This should be prevented by the jar.

**Comment by ArMiN231** [comment]
Never have i seen that problem but as Psycho stated it would be problem of the plugin and not the overworld. I close this
