### ISSUE TITLE
ADD LAVA and WATER In CAVE

### ISSUE THREAD

**Issue by IPECTER** [IrisDimensions/overworld#236]
### Adding, Removing, or Changing

Adding

### Type of Modification

Object

### What are you trying to modify

plz ADD LAVA and WATER In CAVE

### Minecraft Version

1.17.1

### Iris Version

1.9

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
There usually is, its a problem with the JAR, not much i can do if its not even supported lol

**Comment by ArMiN231** [comment]
Done
