### ISSUE TITLE
Trees spawn in the air

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#24]
Trees in the swamp just spawn in the air
**Server and Plugin Informations:**
- Installed plugins: Iris
- Last build github
- PaperSpigot 1.16.5 #629]:
- Operating System (if applicable): 7 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
- Biome: SWAMP
- Overworld versions: v2

![2021-05-15_11 41 23](https://user-images.githubusercontent.com/68811273/118354870-c96b8500-b575-11eb-8605-d00fde11e85e.png)
![2021-05-15_11 41 26](https://user-images.githubusercontent.com/68811273/118354877-d38d8380-b575-11eb-9422-56a953cedcad.png)

**Comment by CocoTheOwner** [comment]
Please specify the name of the object and biome name next time. It's very simple commands. Saves us a lot of time.

**Comment by EneRGO22** [comment]
> Please specify the name of the object and biome name next time. It's very simple commands. Saves us a lot of time.

The screenshot is. But next time I will write in the description to make it easier for you

**Comment by CocoTheOwner** [comment]
Oh I missed that. Sorry. thought I only saw the screenshot-was-taken message pop up.

**Comment by CocoTheOwner** [comment]
Patched on latest. Lmk if it still happens though.
