### ISSUE TITLE
Tropical region doesn't generate.

### ISSUE THREAD

**Issue by PaintsplattersMC** [IrisDimensions/overworld#241]
### Describe the problem

Tropical biomes defined in the regions folder and overworld.json do not generate anywhere in the world.

(only changes i have made are removing the hostile spawners and added some custom ores to overworld.jsons ore generator))

I changed my world to ```new4``` in server.properties to make sure my other world was not interfering.

I generated the world with iris generator in bukkit.yml

I and admins have explored 10s of thousands of blocks in every direction and have not found any biomes listed in the tropical region.

Have tried with multiple seeds. Additionally, there seems to be a disproportionate amount of icy biomes 
I will upload pastebin links of overworld.json and tropical region json files. and a zip of everything in the overworld pack.

Region.json -> https://pastebin.com/X17BmrUu  

[pack.zip](https://github.com/IrisDimensions/overworld/files/7697970/pack.zip)

Overworld.json -> https://pastebin.com/G45GiGB9

### What Should Happen

Tropical biomes should generate.

### Minecraft Version

1.17.1

### Iris Version

1.9.3

### Relevant log output. (IF APPLICABLE)

https://pastebin.com/9Jcw3ZhZ

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by PaintsplattersMC** [comment]
bump

**Comment by ArMiN231** [comment]
It was fixed and i've seen it a lot today therefore i close this
