### ISSUE TITLE
"Iris v1.9.5-1.17.X generated an exception"

### ISSUE THREAD

**Issue by rad1914** [IrisDimensions/overworld#243]
### Describe the problem

Iris throws an exception on my server while running, this happens right after upgrading to iris 1.9.5

### What Should Happen

Actually in a usual behavior there should be no problems when executing it, but iris sometimes generates error spamming while exploring the map

### What Biome

Everywhere

### Object Id

Not specified

### Minecraft Version

1.17.1

### Iris Version

v1.9.5-1.17.X

### Relevant log output. (IF APPLICABLE)

https://pastebin.com/MVtUVeGL

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ArMiN231** [comment]
This is the github repo of the overworld and not the plugin itself. I therefore close this
