### ISSUE TITLE
Walls of world generation stone appear between the joints of rooms in stronghold

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#25]
Walls of stone appear between the joints of rooms in stronghold, I think this is for the reason that when a room with a room spawns there is no block that, in any situation, should not be replaced by other generation blocks

**Server and Plugin Informations:**
- Installed plugins: Iris
- Last build github
- PaperSpigot 1.16.5 #629]:
- Operating System (if applicable): 5 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
- Objects: Stronghold
- Overworld versions: v2.2

![2021-05-15_11 19 54](https://user-images.githubusercontent.com/68811273/118354989-63cbc880-b576-11eb-8b85-1b709a5e3bfd.png)
![2021-05-15_11 20 12](https://user-images.githubusercontent.com/68811273/118354990-68907c80-b576-11eb-9880-bb5d74d8bb54.png)
![2021-05-15_11 20 19](https://user-images.githubusercontent.com/68811273/118354993-6b8b6d00-b576-11eb-8c32-52988cd544a1.png)
![2021-05-15_11 20 31](https://user-images.githubusercontent.com/68811273/118354996-6cbc9a00-b576-11eb-8d55-c722ec484dfc.png)
![2021-05-15_11 20 36](https://user-images.githubusercontent.com/68811273/118354999-6f1ef400-b576-11eb-9e1f-ea318470725b.png)

**Comment by CocoTheOwner** [comment]
Partly intentional. Bug turns into feature, basically.

**Comment by EneRGO22** [comment]
> Partly intentional. Bug turns into feature, basically.

A feature of the hide rooms type?

**Comment by CocoTheOwner** [comment]
Yeah it's to make it somewhat more challenging to simply run around and find everything instantly.

**Comment by EneRGO22** [comment]
> Yeah it's to make it somewhat more challenging to simply run around and find everything instantly.

I don't see the point, it’s clear there is a room next ..
1. There is a step on top and you can look into it what is next (Look into the hole of the step and see if there is a room further)
2.1 wall is very small, a player like me above will just look into the hole of the step, or simply break 1 block and understand that there is something there
3. The tunnel to the next room is too intuitive that there is another room, probably you need to make a couple of entrances

**Comment by NextdoorPsycho** [comment]
This is a jigsaw issue, not an iris issue, tag this issue on the iris jar  repo
