### ISSUE TITLE
Requesting: Waterfalls

### ISSUE THREAD

**Issue by Rabbit0w0** [IrisDimensions/overworld#256]
### Adding, Removing, or Changing

Adding

### Type of Modification

Biome / Region

### What are you trying to modify

I think there should be waterfalls in the Hot regions. That makes the world much cooler😎 

### Minecraft Version

Minecraft 1.18.1

### Iris Version

v1.9.8

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by CocoTheOwner** [comment]
👍

**Comment by ArMiN231** [comment]
I think that isn’t possible atm due to limitations. Atm there aren’t any rivers and lakes. That system needs to be created and maybe a feature of that would be waterfalls. I would say that it isn’t a matter of the overworld settings but a plugin feature.

**Comment by NextdoorPsycho** [comment]
This is possible, but id much rather make it when cyber makes a valid implementation noted tho
