### ISSUE TITLE
Decorator spawning blocks in rows of 3

### ISSUE THREAD

**Issue by TheHappyHopper** [IrisDimensions/overworld#257]
### Describe the problem

The decorator seems to be spawning many blocks in rows of 3 (buttons, sugarcane, mushrooms, kelp, coral, etc...
![2022-01-30_12 23 59](https://user-images.githubusercontent.com/66880702/151716955-fd6a6e98-fcb5-4247-a58a-53f74ff66a9d.png)
![2022-01-30_12 24 04](https://user-images.githubusercontent.com/66880702/151716968-5d82d152-c779-4011-b7e7-cfe9ca81b700.png)
)

### What Should Happen

Decorator should be spawning only one of an item.

### Minecraft Version

1.18.1

### Iris Version

1.9.8

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
we tweaked random recently so give this another try, could be walls tho so not sure
