### ISSUE TITLE
Compatibility Issues with Oh The Dungeons You'll Go

### ISSUE THREAD

**Issue by ktcrow** [IrisDimensions/overworld#259]
### Describe the problem

I would like to preface this ticket by saying that I already consulted with the support team via Discord earlier today and was told I should get in contact with the developer of OTD, which I did, but they requested that I open a ticket here so that they can get more information about what exactly is going wrong between these two plugins.  So, my apologies.  Here is the link for the ticket on the OTD GitHub: https://github.com/OhTheDungeon/OhTheDungeon/issues/39.

I used to use these two plugins together (Iris and Oh The Dungeons) in 1.16.5 with no issues. Together, these two plugins created one of my player's favorite things about the server.  Now I am trying to update my server to 1.18.1, but the new world height is causing a clash.  Essentially, the dungeons from OTD generate 60 blocks in the air (screenshots below).  I obviously do not know the inner workings of each plugin, but my guess would be that since Iris uses y0 as the minimum while generating and then moves the map down by 60 blocks, the dungeons from OTD are generating before this change in the Y coordinate is made, and so they float where they were originally generated.

**I am NOT expecting you, the Iris devs, to change your entire world generation algorithm to compensate for this one plugin**, but I would appreciate any pertinent information you can give that might help the OTD developers create some kind of compatibility so that these two excellent plugins can work their magic together once again.

![otd problem 2](https://user-images.githubusercontent.com/49538849/152911648-f30c0c3b-1f00-4a7b-894c-461ea140fd49.png)
![otd problem 1](https://user-images.githubusercontent.com/49538849/152911630-b27d0262-a6f7-42ba-9371-908ce5f1395b.png)

### What Should Happen

Structures should be generating at ground level.

### Minecraft Version

Minecraft 1.18.1

### Iris Version

1.9.9-1.18.X

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by ArMiN231** [comment]
One dirty way to solve your problem would be pregenerating the world with iris. After that is done, you can add Oh Dungeons so it won’t spawn their structures with a 64 block offset. You need to limit your world with worldborder or something like that thou.

**Comment by OhTheDungeon** [comment]
> One dirty way to solve your problem would be pregenerating the world with iris. After that is done, you can add Oh Dungeons so it won’t spawn their structures with a 64 block offset. You need to limit your world with worldborder or something like that thou.

It won't help I'm afraid. For now OTD uses a built-in config of world (which will set the bottom, sealevel and sky height of a world). It seems that it doesn't match the case of Iris.
The trouble is, it seems that different versions of Iris may have different setting of those three values. Is there any API to get those values from Iris?

**Comment by ArMiN231** [comment]
> > One dirty way to solve your problem would be pregenerating the world with iris. After that is done, you can add Oh Dungeons so it won’t spawn their structures with a 64 block offset. You need to limit your world with worldborder or something like that thou.
> 
> It won't help I'm afraid. For now OTD uses a built-in config of world (which will set the bottom, sealevel and sky height of a world). It seems that it doesn't match the case of Iris. The trouble is, it seems that different versions of Iris may have different setting of those three values. Is there any API to get those values from Iris?

Maybe this can help? https://github.com/VolmitSoftware/Iris#iris-toolbelt
