### ISSUE TITLE
The trees are burning near the lava

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#26]
Trees that appear near the lava in the biome of the volcano start to burn and when they burn down they spoil the appearance of the generation.

**Server and Plugin Informations:**
- Installed plugins: Iris
- Last build github
- PaperSpigot 1.16.5 #629]:
- Operating System (if applicable): 5 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
- Objects: Stronghold
- Overworld versions: v2.2

![2021-05-14_17 16 32](https://user-images.githubusercontent.com/68811273/118355104-f8362b00-b576-11eb-8430-78f1be5c22cc.png)

**Comment by NextdoorPsycho** [comment]
This is a vanilla mechanic, we cant stop trees from burning, im sure that you've seen vanilla trees by lava burn down.
