### ISSUE TITLE
Drip leaf and spore blossom placement

### ISSUE THREAD

**Issue by ghost** [IrisDimensions/overworld#261]
### Describe the problem

Problem
Install Iris and generate a world
Login to server
Check caves for spore blossoms and drip leaf
You may see a very small amount of drip leaf but you won't see any spore blossoms at all
I've also tried cranking up the energy, giving infinite energy, but I'm not sure if this actually has any affect on place spawning.

Solution
No response

Minecraft Version
1.18

Iris Version
1.9.8-1.18.X

Log
https://mclo.gs/YgMvKCH

THIS IS A COPY PASTE ISSUE FROM THE IRIS PLUGIN GITHUB.
https://github.com/VolmitSoftware/Iris/issues/739

### What Should Happen

.

### Minecraft Version

1.18

### Iris Version

LATEST

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Try on latest, i added sporeblossoms from a PR
