### ISSUE TITLE
Sugar cane fly spawn above the grass

### ISSUE THREAD

**Issue by YKDZ** [IrisDimensions/overworld#269]
### Describe the problem

![Snipaste_2022-05-21_18-19-43](https://user-images.githubusercontent.com/69898831/169647268-b0e2e264-839b-4323-b910-421a799af431.png)

### What Should Happen

Maybe the sugar cane can check if their are some object below himself when spawn. 

### Minecraft Version

Minecraft 1.18

### Iris Version

2.1.0-1.18.2

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Might add a Deco Priority system

**Comment by NextdoorPsycho** [comment]
Should be fixed now, Was a jar issue
