### ISSUE TITLE
Frame with eye ender

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#27]
I propose to make such a chip in the portal generation, which is in vanilla minecraft, so that when the portal is generated, the frame can get a chance to spawn a frame with an eye ender

**Server and Plugin Informations:**
- Installed plugins: Iris
- Last build github
- PaperSpigot 1.16.5 #629]:
- Operating System (if applicable): 5 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
- Objects: Stronghold
- Overworld versions: v2.2

**Comment by NextdoorPsycho** [comment]
might actually do this at some point

**Comment by ArMiN231** [comment]
> might actually do this at some point

The problem is that iris doesn’t properly save the rotations of blocks as far as I remember correctly

**Comment by CocoTheOwner** [comment]
Needs to be added by the plugin first. Needs NBT tags.

**Comment by StrangeOne101** [comment]
Nah, this can be done right now. The portal frame blocks use block data for the eyes

**Comment by CocoTheOwner** [comment]
Added. [pull 57](https://github.com/IrisDimensions/overworld/pull/57).
