### ISSUE TITLE
Add water rivers to the biomes

### ISSUE THREAD

**Issue by fendyk** [IrisDimensions/overworld#270]
### Adding, Removing, or Changing

Adding

### Type of Modification

Biome / Region

### What are you trying to modify

Like the title says, add rivers as the default Minecraft generation.

### Minecraft Version

Minecraft 1.18.2

### Iris Version

2.2.1

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by NextdoorPsycho** [comment]
I would need to have the Jar have a better implementation to be able to do this, but trust me, i want it too :(((
