### ISSUE TITLE
Deeper depths

### ISSUE THREAD

**Issue by RePixelatedMC** [IrisDimensions/overworld#271]
### Adding, Removing, or Changing

Changing

### Type of Modification

Biome / Region

### What are you trying to modify

Make the world deeper like -512 for more content ( caves structures etc )

### Minecraft Version

1.18

### Iris Version

*

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by svdgoor** [comment]
Performance of worlds of that size is bad. Even after pregen clients will have issues rendering it. But I do like the idea

**Comment by NextdoorPsycho** [comment]
Wrong Github, Go to iris DImensions, and ask them / those pack creators.
https://github.com/IrisDimensions
