### ISSUE TITLE
End World Generation

### ISSUE THREAD

**Issue by GabikaPasta** [IrisDimensions/overworld#272]
### Adding, Removing, or Changing

Changing

### Type of Modification

Other

### What are you trying to modify

Minecraft's end world is boring.

### Minecraft Version

1.19

### Iris Version

2.2.0 (Test Build for 1.19)

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by svdgoor** [comment]
Can you tell us
1. Why the end is boring
2. What you would like to see us make

**Comment by NextdoorPsycho** [comment]
a: Not iris's problem, we are an engine, not the pack creators
b: if you want a cool end, make it!
c: If you do let me know and ill add it to the github where we host public packs
