### ISSUE TITLE
Height

### ISSUE THREAD

**Issue by Comquister** [IrisDimensions/overworld#284]
### Adding, Removing, or Changing

Changing

### Type of Modification

Other

### What are you trying to modify

make the world lower to sea level like the vanilla version

Example:
```
    },
    "logicalHeight": 512,
    "dimensionHeight": {
        "max": 584,
        "min": -72
    },
```

### Minecraft Version

Minecraft 1.19

### Iris Version

v2.2.1-1.19

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by Comquister** [comment]
Correcting
```
    "version": 2085,
    "name": "Overworld",
    "environment": "NORMAL",
    "fluidHeight": 64,
    "continentZoom": 1,
    "continentalStyle": {
        "style": "NOWHERE_CELLULAR",
        "zoom": 5
    },
    "logicalHeight": 512,
    "dimensionHeight": {
        "max": 608,
        "min": -96
    },
```

**Comment by didkoti** [comment]
The default fluid height is 63, also I don't see why would u have the fluid height so low if you want the world to be 600 y+

But personally I'm also for the idea to have a vanillalike-ish deepslate underground, not that I have any right to have an opinion tho lol

**Comment by NextdoorPsycho** [comment]
> The default fluid height is 63, also I don't see why would u have the fluid height so low if you want the world to be 600 y+
> 
> But personally I'm also for the idea to have a vanillalike-ish deepslate underground, not that I have any right to have an opinion tho lol

The deepslate thing IS possible, and ill even add it to the TodoList for the Overworld, other pack creators will need to do whatever they want, as we dont control them.



> ### Adding, Removing, or Changing
> Changing
> 
> ### Type of Modification
> Other
> 
> ### What are you trying to modify
> make the world lower to sea level like the vanilla version
> 
> Example:
> 
> ```
>     },
>     "logicalHeight": 512,
>     "dimensionHeight": {
>         "max": 584,
>         "min": -72
>     },
> ```
> 
> ### Minecraft Version
> Minecraft 1.19
> 
> ### Iris Version
> v2.2.1-1.19
> 
> ### Checklist
> * [x]  I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
> * [x]  I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

This is not safe, You should set your Logical Height to be whatever your max height is or you will have issues. 

> Correcting
> 
> ```
>     "version": 2085,
>     "name": "Overworld",
>     "environment": "NORMAL",
>     "fluidHeight": 64,
>     "continentZoom": 1,
>     "continentalStyle": {
>         "style": "NOWHERE_CELLULAR",
>         "zoom": 5
>     },
>     "logicalHeight": 512,
>     "dimensionHeight": {
>         "max": 608,
>         "min": -96
>     },
> ```

This is also unsafe. 

**ALL HEIGHT NEEDS TO BE IN INCREMENTS OF 8 TOTAL**
For example |-64|  + 448 = 512 you can have a total eorld height of, 8, 16, 32,...512...1024... etc
Doing anything else will make your server shit itself.


As for the worldHeight thing, This is not our job, go tell the pack creators that you want the fluid height changed, or change it yourself. you have -+3k to work with in terms of depth im sure you can figure it out
