### ISSUE TITLE
Steve tree

### ISSUE THREAD

**Issue by 94ekhero** [IrisDimensions/overworld#285]
### Describe the problem

My player found this on my iris overworld 
![2022-07-09_15 38 36](https://user-images.githubusercontent.com/107491882/178096629-1bf4cc26-8e7e-4700-8988-a03911c41f5b.png)

coordinate: 2266 189 -3291

### What Should Happen

lol the steve's head should something else i guess

### What Biome

It responds null (THE_VOID)

### Object Id

Nothing happend when using the dust.

### Minecraft Version

MInecraft 1.19

### Iris Version

2.2.2

### Relevant log output. (IF APPLICABLE)

https://mclo.gs/sg8Sjkc

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
can you hit this with /iris object dust
this was an old easteregg

**Comment by NextdoorPsycho** [comment]
Inactive
