### ISSUE TITLE
Support for MythicMobs RandomSpawn conditions in Carving regions/biomes

### ISSUE THREAD

**Issue by scarlettcloud** [IrisDimensions/overworld#288]
It would be great if it was possible to define underground/cave regions as biomes for the purposes of MythicMobs RandomSpawn configuration,

In initial testing (Purpur server, Iris-2.2.9, MythicMobs 5.1.1), existing RandomSpawn conditions are limited to overworld Biome types, or setting conditions for things like biometype{t=underground} which prohibits the user from setting more specific cave spawns for mobs (for example, specific to lush or dripstone or amethyst caves). 

Let me know if there's additional information I can provide / detail I can add!

**Comment by ghost** [comment]
@scarlettcloud you picked the wrong GitHub repo. This is the repo for the overworld pack, not the plugin. 
see this -> https://github.com/VolmitSoftware/Iris/issues

**Comment by scarlettcloud** [comment]
Thanks!
