### ISSUE TITLE
Request custom biome color list

### ISSUE THREAD

**Issue by Mengbill** [IrisDimensions/overworld#289]
### Adding, Removing, or Changing

Adding

### Type of Modification

Other

### What are you trying to modify

Request custom biome color list.

Some plugins needs the biome color setted to render the map properly. like this↓
https://github.com/BillyGalbreath/Pl3xMap/wiki/3rd-Party-World-Generators

### Minecraft Version

Minecraft 1.19

### Iris Version

Iris-2.2.12-1.19.2

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by svdgoor** [comment]
Custom biome colors can be found in the datapack. Any plugin not using that data is instantly incompatible with all datapacks using custom colors.
Iris doesn't do anything different from regular datapacks.

**Comment by svdgoor** [comment]
Looking at the repo you sent, they are taking a bad approach. They're manually color coding datapacks from which you can literally get the colors directly. No point.

**Comment by Mengbill** [comment]
Thanks a lot. And i tried to manually write the custom biome color in the advance.yml but i got this error. Does it mean it is incompatiable with iris world gen?
![02](https://user-images.githubusercontent.com/36590590/188876217-6ca8e161-03d0-4393-9df0-957ae1fdf8b4.png)
![001](https://user-images.githubusercontent.com/36590590/188876228-f36ba58f-5240-40ba-9d34-d4d1115ec79b.png)

**Comment by svdgoor** [comment]
No you made a config errors there's no Minecraft:iris:biome, it's without the Minecraft:. If you remove that it looks like it would work just fine.

**Comment by Mengbill** [comment]
**After many tests, I finally found the correct way to write in the configuration file(advanced.yml)

Now,Squaremap can render the custom biome color correctly!

↓This is the correct advanced.yml file for default overworld pack↓
https://pastebin.com/L098UUps**
