### ISSUE TITLE
Fake Air Blocks, causing Structures and Trees to levitate

### ISSUE THREAD

**Issue by R411gun** [IrisDimensions/overworld#293]
### Describe the problem

When caves generate and push outside the surface, air blocks are "not" air blocks.
This can be tested if you mark the location with worldedit and enter //replace !air stone

![2022-09-21_16 22 21](https://user-images.githubusercontent.com/15186764/191530477-d448a2e6-20f0-470a-9810-9eb52f481c13.png)
![2022-09-21_16 22 27](https://user-images.githubusercontent.com/15186764/191530500-218e7a70-b344-4ecb-b292-5e24f3e0ec7d.png)

![2022-09-21_16 30 11](https://user-images.githubusercontent.com/15186764/191532288-ce1f5060-67ee-4523-850e-42425c2767ff.png)
![2022-09-21_16 30 15](https://user-images.githubusercontent.com/15186764/191532305-49d218df-1ffa-4953-9845-abee2a696a8a.png)

This causes big problems as: 
- Trees sometimes levitate
- Structures sometimes levitate

### What Should Happen

It should be fixed :D

### What Biome

Everywhere where caves push through the surface

### Minecraft Version

1.19.2 (but this happened on previous versions too)

### Iris Version

2.3.0

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
Not a pack issue, This is a jar issue, Caves are generated AFTER things. This will be Fixed in the Iris ReWrite
