### ISSUE TITLE
Biomes not showing up in F3

### ISSUE THREAD

**Issue by Zekernn** [IrisDimensions/overworld#295]
### Describe the problem

Essentially, in the overworld pack for me all biomes appear as "minecraft:plains". I have other Iris dimension packs, and they work just fine. However, my overworld for whatever reason isn't. I created the world properly as instructed via wiki, and I use a compatible world management plugin (MyWorlds). All on the right version.

This issue is huge to me, since I'm working on spawn systems for mythicmobs, which with the messed up biomes in F3, causes issues with that.
![image](https://user-images.githubusercontent.com/63178442/211669667-036f8bc9-ea4e-42bf-b239-f36a17334835.png)

### What Should Happen

The biomes should appear properly in F3, and not just minecraft:plains throughout the overworld.

### What Biome

All / Global

### Object Id

N/A

### Minecraft Version

PurpurMc 1.19.2

### Iris Version

Iris-2.3.5-1.19.2.jar

### Relevant log output. (IF APPLICABLE)

No Errors in log.

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by NextdoorPsycho** [comment]
This is a datapack issue, you need to let the server restart, and be sure to be on the proper pack etc... reach out on discord for more help!
