### ISSUE TITLE
Rarity key for frog-spawn missing

### ISSUE THREAD

**Issue by R411gun** [IrisDimensions/overworld#318]
### Describe the problem

The "rarity": x key is missing for those two files for frogs:
spawners\temperate\water.json
spawners\tropical\water.json

This results in way too many frogs spawning.

Also, for tadpoles, they somehow spawn on land and die shortly after.
Didn't want to open another issue for this

### What Should Happen

I would recommend this config for both mentioned files

"entity": "standard/passive/frog",
           "maxSpawns": 2,
           "minSpawns": 1,
           "rarity": 1

### What Biome

temperate and tropical

### Minecraft Version

1.20.1 but happened on 1.19.4 too

### Iris Version

v2.7.4

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by RePixelatedMC** [comment]
Not needed

**Comment by R411gun** [comment]
I have a high simulation distance of 32 and the world is full of frogs.
For 1 normal animal, there are like 10 frogs

might be a niche usecase, i got it fixed with limiting frogs



simD is that high because it's a gun server, chunk loading speed is limited by paper

**Comment by RePixelatedMC** [comment]
Let me guess you got aikar flags right?

**Comment by R411gun** [comment]
Yes, as I tested it last year and the performance was better
is there a flag that produces this error?

**Comment by RePixelatedMC** [comment]
Aikar breaks the iris inbuild timings so causing to spawn infinite frogs

**Comment by R411gun** [comment]
I tried it and it's just true
woud have never thought of this
thank you!

**Comment by RePixelatedMC** [comment]
np join our discord for any additional information / support and just ping me if you need me
