### ISSUE TITLE
Please update Iris to 1.20.4

### ISSUE THREAD

**Issue by CCjun6** [IrisDimensions/overworld#327]
### Adding, Removing, or Changing

Changing

### Type of Modification

Other

### What are you trying to modify

Please update Iris to 1.20.4

### Minecraft Version

1.20.4

### Iris Version

3.0

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld but know the content suggestion is valid)
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this feature was not already implemented in the latest version.

**Comment by RePixelatedMC** [comment]
Yess yess we know the problem is that the current update is already ready for quite some time so it will be the update after next update

**Comment by INSide-734** [comment]
> Yess yess we know the problem is that the current update is already ready for quite some time so it will be the update after next update

When will the next update be? It's been so long, Minecraft has been updated to 1.21.

**Comment by LUF3N** [comment]
Hello [INSide-734](https://github.com/INSide-734),
the iris dev team will work on that as soon as stable paper builds are avaible.
You can check the paper builds [here](https://papermc.io/downloads/paper)
