### ISSUE TITLE
Stronghold placement

### ISSUE THREAD

**Issue by ArMiN231** [IrisDimensions/overworld#39]
The Placement of the stronghold is totally off. Pieces arent connected.

**Comment by StrangeOne101** [comment]
I can confirm this, but I don't think it's an issue with the stronghold itself. All pieces are fine when edited, and when the stronghold structure is manually placed with `/iris jigsaw place stronghold`, the pieces are connected perfectly. I believe it's got something to do with connections during world generation

**Comment by NextdoorPsycho** [comment]
This is a plugin issue, not an overworld issue ;)
