### ISSUE TITLE
lava in caves not aligning.

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#70]
![afbeelding](https://user-images.githubusercontent.com/65736624/122654935-ea179380-d14e-11eb-851b-838c20aa052d.png)

I think it would be worth filling all caves below y=13 with lava to not have to deal with this anymore.

**Comment by NextdoorPsycho** [comment]
mmmmmm
this is not a terrible idea

**Comment by NextdoorPsycho** [comment]
https://github.com/IrisDimensions/overworld/issues/75

**Comment by CocoTheOwner** [comment]
That's not a duplicate
One is for the cave lava and the other is for the water&lava columns. the screenshots looking alike is on accident. If you agree, reopen please.
