### ISSUE TITLE
oceans are boring

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#73]
![afbeelding](https://user-images.githubusercontent.com/65736624/122654997-5befdd00-d14f-11eb-907b-bc9e6c77f11e.png)

While they look better than vanilla, there's nothing to explore apart from a bunch of rocks.
Shipwrecks, water zombie outposts, custom guardian temples, an old structure similar to the stronghold (but not the same, and clearly distinguishable), more loot, more things that people want to go out and find. Rare stuff. Exploring is what we want people to do!

**Comment by NextdoorPsycho** [comment]
ill add more 👍

**Comment by CocoTheOwner** [comment]
imo they look better now. we can always add more, if someone dares complaining :)
