### ISSUE TITLE
very little entities

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#74]
![afbeelding](https://user-images.githubusercontent.com/65736624/122655109-58108a80-d150-11eb-99ba-aad627ae0b37.png)
Nothing.

![afbeelding](https://user-images.githubusercontent.com/65736624/122655137-8b531980-d150-11eb-9567-93bc8b8300ca.png)
Cows pigs sheep, pretty much random, not many, no clusters, spawning too often.
Recommend increasing the quantity per successful roll, and decreasing the chance to roll successfully.
No horses I can find.

At least bees spawn.
I think we should be spawning mobs in caves by default, at the start only. Especially since we added glowstone (prevents spawns)

This has been something people have been saying for a long time. I think Iris can really do this well.

**Comment by CocoTheOwner** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/122655590-b2f7b100-d153-11eb-83a3-38db9ed89151.png)

Polar bears, no foxes, no snowmen lol

**Comment by CocoTheOwner** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/122655695-a889e700-d154-11eb-9b05-2244f2a50fd8.png)

Rip but at least they spawn

**Comment by NextdoorPsycho** [comment]
lolol

**Comment by NextdoorPsycho** [comment]
ive done what i can in current / past updates. this is a jar issue
