### ISSUE TITLE
Water and lava pillars not high enough

### ISSUE THREAD

**Issue by CocoTheOwner** [IrisDimensions/overworld#75]
![afbeelding](https://user-images.githubusercontent.com/65736624/122655187-f270ce00-d150-11eb-88a1-5081dfb05ddf.png)
I understand why, I understand how, but they're not high enough all the time, especially in those high caves we currently have.
#71 will decrease the occurrence of this, but it will likely still happen regardless.

**Comment by CocoTheOwner** [comment]
If we could choose objects to be placed *on the top of a cave*, we could stilt it down easily. Would be a plugin thing though: [Iris plugin issue request](https://github.com/VolmitSoftware/Iris/issues/380)

**Comment by NextdoorPsycho** [comment]
Ceiling decorator  needs to be implemented, and it will be easier
